version: '3.7'
services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build: 
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
  db:
    image: postgres
    environment: 
      POSTGRES_USER: hard
      POSTGRES_DB: hardware
      POSTGRES_PASSWORD: PASSWORD
    volumes:
      - ~/pgdata:/var/lib/postgresql/data

volumes:
  static:
  pgdata:
      